### ISSUE TITLE
Remove dependency on WebScript before December 15th

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-example-app-files#10]
Webscript shuts down on December 15th and https://github.com/zapier/zapier-platform-example-app-files/blob/master/hydrators.js#L5 is still relying on https://www.webscript.io/script/zapier/platform-example-app/download and https://github.com/zapier/zapier-platform-example-app-files/blob/master/creates/uploadFile.js#L21 relies on https://www.webscript.io/script/zapier/platform-example-app/upload.

Code:

download

```lua
-- Used by the Platform Files Example app (2017-04-17)

if request.method ~= 'GET' then
	return 400, 'Must be GET request'
end

-- We're just pretending to find a file and download, but it's always the same

return 302, {}, {["Location"]="https://cdn.zapier.com/storage/files/f6679cf77afeaf6b8426de8d7b9642fc.pdf"}
```

upload

```lua
-- Used by the Platform Files Example app (2017-04-17)

if request.method ~= 'POST' then
	return 400, 'Must be POST request'
end

local file = request.files.file
-- It's possible to access #file.content though we don't need to

if not file then
	return 400, 'File is required'
end

local filename = request.form.filename or file.filename
local name = request.form.name or filename

if not filename or not name then
	return 400, 'At least filename is required'
end

local data = {
	name = name,
	filename = filename
}

-- Create file in mockapi.io
local response = http.request {
	url = "http://57b20fb546b57d1100a3c405.mockapi.io/api/files",
	method = "POST",
	headers = {["Content-Type"] = "application/json"},
	data = json.stringify(data)
}

return 200, response.content
```

**Comment by BrunoBernardino** [comment]
@bcooksey I'm assigning this to you so you can assign properly (I'll get to this and close it if I've got time before Alix is born)

**Comment by BrunoBernardino** [comment]
This has a similar problem to https://github.com/zapier/zapier-platform-app-dropbox/issues/23, in that it needs Chalice, but for different reasons.

Basically webtask requires a JWT to parse body data (so that we can return different info based on the request data), and because I don't want to muddle this example app, I think it's best to not add that.

**Comment by BrunoBernardino** [comment]
I've been able to use webtask to replace the download portion of it, though.

**Comment by BrunoBernardino** [comment]
https://github.com/zapier/ms-platform-tests has what's left, just waiting for that to be deployed and then will update the URLs here.
